version: '3.9'

services:      
  postgres:
    image: postgres:16.3 #load version 10 to keep in sync with serverless version
    container_name: postgres
    restart: always   
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data      
    networks:
      - nat
      
volumes:
  postgres_data:

networks:
  nat:
    external: true
    name: nat